### ISSUE TITLE
PICMI: Win (Py 3.8) and macOS (PyPy 3.7/73)

### ISSUE THREAD

**Issue by ax3l** [conda-forge/warpx-feedstock#37]
## Failing PICMI tests on two combinations

Tested and seen since #36

### `win win_64_python3.8.____cpython`
(`python:                  3.8.12-h900ac77_2_cpython`)
```
(%PREFIX%) %SRC_DIR%>%PREFIX%\python.exe Examples\Physics_applications\laser_acceleration\PICMI_inputs_3d.py 
Traceback (most recent call last):
Failed to load the libwarpx shared object library
  File "Examples\Physics_applications\laser_acceleration\PICMI_inputs_3d.py", line 124, in <module>
    sim.initialize_warpx()
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\picmi.py", line 1043, in initialize_warpx
    pywarpx.warpx.init(mpi_comm)
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\WarpX.py", line 79, in init
    libwarpx.initialize(argv, mpi_comm=mpi_comm)
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\_libwarpx.py", line 423, in initialize
    self.amrex_init(argv, mpi_comm)
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\_libwarpx.py", line 408, in amrex_init
    self.libwarpx_so.amrex_init(argc, argvC)
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\_libwarpx.py", line 61, in __getattr__
    self.load_library()
  File "D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\_libwarpx.py", line 111, in load_library
    self.libwarpx_so = ctypes.CDLL(os.path.join(self._get_package_root(), libname))
  File "D:\bld\warpx_1641463451911\_test_env\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\bld\warpx_1641463451911\_test_env\lib\site-packages\pywarpx\libwarpx.3d.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Maybe related to:
- https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python
- https://bugs.python.org/issue42114

CPython 3.7 and 3.9 builds & tests work fine.

### `osx osx_64_python3.7.____73_pypy`
```
+ /Users/runner/miniforge3/conda-bld/warpx_1641463532773/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python Examples/Physics_applications/laser_acceleration/PICMI_inputs_3d.py
amrex::Error::0::Couldn't open file: ��l� !!!
SIGABRT
See Backtrace.0.0 file for details
```

Fix for the PyPy issue in #38

**Comment by ax3l** [comment]
I think the first problem went away in 22.04+
